### PR TITLE
add nodePort support

### PR DESCRIPTION
**Pull request by survivant**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. helm upgrade on minikube, helm install on gke)

### CODE REVIEW

**Comment by redsk** [comment]
Hey @survivant thanks for creating the PR here :) 

I've been reviewing the changes and I think that the deployment could fail when the number of replicas is greater than 1 as the node port is fixed. Shouldn't an approach similar to what Confluent did for `cp-kafka` (see `charts/cp-kafka/templates/nodeport-service.yaml`) be applied here? They create one service per replica, there.

**Comment by survivant** [comment]
any help is welcome.  In my case I tested long ago with only 1 replica

**Comment by gAmUssA** [comment]
kindly rebase @survivant

**Comment by survivant** [comment]
@gAmUssA is it ok ?

**Pull request closed without merging**
